Repository netgrif/application-builder, pull requests merged in 2024-01, with the labels that each got.

#2 converter URL and bpmn.io stylesheet update
  nae.json
  src/app/modeler/control-panel/control-panel.component.ts
  src/app/modeler/edit-mode/bpmn-mode/bpmn-edit.service.ts
  src/app/modeler/edit-mode/bpmn-mode/bpmn-mode-editor/bpmn-mode-editor.component.ts
  src/app/modeler/edit-mode/bpmn-mode/customModules/custom-context-pad-provider.ts
  src/styles.scss
Labels: bug, Extra Small

#3 [NAB-327] - Release 4.0.0
  src/app/modeler/edit-mode/context-menu/menu-items/select-arcs-menu-item.ts
  src/app/modeler/edit-mode/services/modes/quick-draw-tool.ts
  src/app/modeler/edit-mode/services/modes/select-tool.ts
Labels: Extra Small

#5 [NAB-327] - Release 4.0.0
  src/app/modeler/edit-mode/edit-mode.component.html
  src/app/modeler/edit-mode/edit-mode.service.ts
  src/app/modeler/edit-mode/services/modes/add-token-tool.ts
  src/app/modeler/edit-mode/services/modes/canvas-tool.ts
  src/app/modeler/edit-mode/services/modes/create-arc-tool.ts
  src/app/modeler/edit-mode/services/modes/create-place-tool.ts
  src/app/modeler/edit-mode/services/modes/create-ptarc.ts
  src/app/modeler/edit-mode/services/modes/create-regular-arc-tool.ts
  src/app/modeler/edit-mode/services/modes/create-transition-tool.ts
  src/app/modeler/edit-mode/services/modes/quick-draw-tool.ts
  src/app/modeler/edit-mode/services/modes/remove-token-tool.ts
  src/app/modeler/edit-mode/services/modes/select-tool.ts
  src/app/modeler/services/canvas/canvas-listener-tool.ts
  src/app/modeler/services/canvas/listeners/arc-listener.ts
  src/app/modeler/services/canvas/listeners/context-menu-interruption-error.ts
  src/app/modeler/services/canvas/listeners/key-listener.ts
  src/app/modeler/services/canvas/listeners/mouse-listener.ts
  src/app/modeler/services/canvas/listeners/place-listener.ts
  src/app/modeler/services/canvas/listeners/transition-listener.ts
  src/app/modeler/simulation-mode/tool/event-simulation.tool.ts
  src/app/modeler/simulation-mode/tool/simulation-tool.ts
  src/app/modeler/simulation-mode/tool/task-simulation.tool.ts
Labels: Extra Large

#6 [NAB-327] - Release 4.0.0
  src/app/dialogs/dialog-model-edit/dialog-model-edit.component.html
  src/app/dialogs/dialog-model-edit/dialog-model-edit.component.ts
  src/app/modeler/edit-mode/context-menu/menu-items/model/edit-model-menu-item.ts
  src/app/modeler/services/model/model-config.ts
  src/app/modeler/services/model/model.service.ts
  src/assets/mortgage_simple.xml
Labels: Extra Small
